name: shopify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.2
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.15
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.2
  iconsax: ^0.0.8
  intl: ^0.19.0
  logger: ^2.4.0
  lottie: ^3.1.3
  readmore: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/icons/brands/
    - assets/images/user/
    - assets/images/reviews/
    - assets/icons/payment_methods/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
